# Generated by Django 6.0.1 on 2026-02-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('partial', 'Partial')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('partial', 'Partial')], max_length=20, null=True),
        ),
    ]
