# Generated by Django 6.0.1 on 2026-02-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'Habsify Bank Account'},
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='features',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.ManyToManyField(blank=True, to='subscriptions.feature'),
        ),
    ]
