# Generated by Django 6.0.1 on 2026-02-20 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('sales_purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='linked_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='sales_purchases.purchase'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='linked_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='sales_purchases.sale'),
        ),
    ]
