# Generated by Django 6.0.1 on 2026-02-20 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales_purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='sales_purchases.purchase'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='sales_purchases.sale'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.company'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('item', 'warehouse')},
        ),
    ]
