# Generated by Django 6.0.1 on 2026-02-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_item_code_item_company_item_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-date']},
        ),
    ]
