# Generated by Django 6.0.1 on 2026-02-20 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0003_stockmovement_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'inventories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'items'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-date'], 'verbose_name_plural': 'stock movements'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['name'], 'verbose_name_plural': 'warehouses'},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='company',
        ),
        migrations.AddField(
            model_name='inventory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='core.company'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('company', 'item', 'warehouse')},
        ),
    ]
