# Generated by Django 6.0.1 on 2026-02-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_used_trial',
            field=models.BooleanField(default=False),
        ),
    ]
